STEP1 - 간단 자동차 경주 구현
seok-2-o/java-racingcar pull request #1
Opened 2020-12-11 09:30 UTC by seok-2-o

2020-12-11 11:32 UTC, jaeyeonling requested changes
오랜만에 소소한 피드백 남겼습니다 🔥

2020-12-11 11:32 UTC, jaeyeonling commented on build.gradle
> +sourceCompatibility = 1.11
```suggestion
sourceCompatibility = JavaVersion.VERSION_11
```

2020-12-11 11:32 UTC, jaeyeonling commented on src/main/java/application/RacingGameApplication.java
> +        while(game.isNotEnd()) {
```suggestion
        while (game.isNotEnd()) {
```

2020-12-11 11:32 UTC, jaeyeonling commented on src/main/java/data/domain/Car.java
> +            position ++;
```suggestion
            position++;
```

2020-12-11 11:32 UTC, jaeyeonling commented on src/main/java/data/domain/RacingGame.java
> +    public int [] move() {
```suggestion
    public List<Integer> move() {
```

이펙티브 자바 `아이템 28. 배열보다는 리스트를 사용하라`를 참고해보면 어떨까요?

2020-12-11 11:32 UTC, jaeyeonling commented on src/main/java/data/domain/RacingGame.java
> +            .mapToInt(car -> car.move(RANDOM.nextInt(ENGINE_MAX_POWER)))
랜덤한 요소를 Car에서 분리하여 Car는 테스트할 수 있는 구조가 됐지만, RacingGame은 아직 테스트가 힘드네요!
RacingGame도 테스트하기 좋은 구조로 변경해보면 어떨까요?

2020-12-11 11:32 UTC, jaeyeonling commented on src/main/java/data/domain/RacingGame.java
> +        if(laps == END_GAME_LAPS) {
```suggestion
        if (laps <= END_GAME_LAPS) {
```

어떠한 이유로 laps가 -1이 된다면 해당 예외처리는 동작하지 않을 수 있습니다!
범위의 검증은 위와 같이 처리하는 습관을 들여보시면 어떨까요?

2020-12-11 11:32 UTC, jaeyeonling commented on src/test/java/data/domain/CarTest.java
> +    @DisplayName("자동차 이동 테스트 - 4 보다 크면 전진한다.")
```suggestion
    @DisplayName("자동차 이동 테스트 - " + Car.THRESHOLD  + " 보다 크면 전진한다.")
```

조건이 변경 됐을 때 해당 테스트의 DisplayName을 신경쓰지 않으면 더 좋겠어요 :)

2020-12-11 11:57 UTC, seogi89 commented on src/main/java/application/RacingGameApplication.java
> +        while(game.isNotEnd()) {
이번에 IDE 없이 개발해보자 싶어서( 포비님이 예전에 말씀 하신 컴포트존을 벗어나기 위해) vim을 써봤는데 저는 IDE의 노예 였습니다. 😢

2020-12-11 23:59 UTC, seogi89 commented on src/test/java/data/domain/CarTest.java
> +    @DisplayName("자동차 이동 테스트 - 4 보다 크면 전진한다.")
오 좋네요. 다만 지금은 상수의 가시성을 변경해야하는데 이부분에 대해서 고민이 있네요 ㅎ
별도로 비지니스의 상수를 관리하는 파일을 만들거나 `.properties` 를 사용하는 것도 좋겠네요.

2020-12-12 00:03 UTC, seogi89 commented on src/main/java/data/domain/RacingGame.java
> +    public int [] move() {
최대한 심플하게 만들어보고 싶었는데, 사소한 것도 잘 챙겨야 견고한 소프트웨어를 만들 수 있겠죠! 🙇

2021-12-14 12:51 UTC, closed without merging